version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: unpo_admin
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: unpo_nora_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: unpo_backend

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Optional: Simple DB GUI for easier development
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    container_name: unpo_frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    user: root
    command: npm run dev
    depends_on:
      - backend
    networks:
      - backend-network

volumes:
  postgres_data:


networks:
  backend-network:
