"""add assigned_seller_phone to lead

Revision ID: c9e8340fc9d6
Revises: b8e7239fb8c5
Create Date: 2026-05-12 11:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c9e8340fc9d6'
down_revision: Union[str, None] = 'b8e7239fb8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('assigned_seller_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'assigned_seller_phone')
    # ### end Alembic commands ###
