"""Add detailed leads table

Revision ID: d50c8f471238
Revises: 1d74bcbcf943
Create Date: 2026-02-20 02:30:44.643591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd50c8f471238'
down_revision: Union[str, None] = '1d74bcbcf943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('purchase_volume', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('category_interest', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('product_interest', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('campaign', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('ad_set', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('ad_name', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('seller', sa.String(), nullable=True))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_leads_full_name'), 'leads', ['full_name'], unique=False)
    op.drop_column('leads', 'company_name')
    op.drop_column('leads', 'interest_data')
    op.drop_column('leads', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('interest_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_leads_full_name'), table_name='leads')
    op.alter_column('leads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('leads', 'seller')
    op.drop_column('leads', 'platform')
    op.drop_column('leads', 'ad_name')
    op.drop_column('leads', 'ad_set')
    op.drop_column('leads', 'campaign')
    op.drop_column('leads', 'product_interest')
    op.drop_column('leads', 'experience_level')
    op.drop_column('leads', 'category_interest')
    op.drop_column('leads', 'purchase_volume')
    op.drop_column('leads', 'full_name')
    # ### end Alembic commands ###
