"""add whatsapp multi-agent data model

Revision ID: efa066dfdf30
Revises: 71e9e987f7d2
Create Date: 2026-07-17 13:36:23.051814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Modelo de datos WhatsApp Cloud API multiagente (Etapa 1B). 10 tablas whatsapp_*.
# Diseño en docs/unpo-whatsapp-cloud-api-architecture.md.
#  - Estados como String (NO enums PG nativos) -> evita ALTER TYPE a futuro.
#  - Idempotencia: índices únicos PARCIALES en whatsapp_messages
#    (provider,external_message_id) y (client_request_id) sólo cuando no son NULL.
#  - JSONB en safe_payload / raw_payload; UUID en client_request_id.
#  - FK circular conversation_reads -> messages resuelta con op.create_foreign_key()
#    tras crear ambas tablas (ver upgrade/downgrade).
#  - NO crea whatsapp_media (queda para una etapa posterior).
#  - NO toca tablas comerciales.

# revision identifiers, used by Alembic.
revision: str = 'efa066dfdf30'
down_revision: Union[str, None] = '71e9e987f7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('phone_number_id', sa.String(length=128), nullable=False),
    sa.Column('waba_id', sa.String(length=128), nullable=False),
    sa.Column('display_number', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'display_number', name='uq_whatsapp_lines_provider_display_number'),
    sa.UniqueConstraint('provider', 'phone_number_id', name='uq_whatsapp_lines_provider_phone_number_id')
    )
    op.create_table('whatsapp_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_safe', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_key', name='uq_whatsapp_webhook_events_provider_event_key')
    )
    op.create_index('ix_whatsapp_webhook_events_raw_payload_expires_at', 'whatsapp_webhook_events', ['raw_payload_expires_at'], unique=False)
    op.create_index('ix_whatsapp_webhook_events_status_received', 'whatsapp_webhook_events', ['processing_status', 'received_at'], unique=False)
    op.create_table('whatsapp_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whatsapp_contacts_lead_id', 'whatsapp_contacts', ['lead_id'], unique=False)
    op.create_table('whatsapp_line_user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('can_send', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['whatsapp_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'user_id', name='uq_whatsapp_line_user_access_line_user')
    )
    op.create_index('ix_whatsapp_line_user_access_line_id', 'whatsapp_line_user_access', ['line_id'], unique=False)
    op.create_index('ix_whatsapp_line_user_access_user_id', 'whatsapp_line_user_access', ['user_id'], unique=False)
    op.create_table('whatsapp_contact_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('identifier_type', sa.String(length=32), nullable=False),
    sa.Column('identifier_value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'identifier_type', 'identifier_value', name='uq_whatsapp_contact_identifiers_value')
    )
    op.create_index('ix_whatsapp_contact_identifiers_contact_id', 'whatsapp_contact_identifiers', ['contact_id'], unique=False)
    op.create_index('ix_whatsapp_contact_identifiers_identifier_value', 'whatsapp_contact_identifiers', ['identifier_value'], unique=False)
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignment_source', sa.String(length=32), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_service_window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_id'], ['whatsapp_lines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'contact_id', name='uq_whatsapp_conversations_line_contact')
    )
    op.create_index('ix_whatsapp_conversations_assigned_status_last_msg', 'whatsapp_conversations', ['assigned_user_id', 'status', 'last_message_at'], unique=False)
    op.create_index('ix_whatsapp_conversations_contact_id', 'whatsapp_conversations', ['contact_id'], unique=False)
    op.create_index('ix_whatsapp_conversations_lead_id', 'whatsapp_conversations', ['lead_id'], unique=False)
    op.create_index('ix_whatsapp_conversations_line_status_last_msg', 'whatsapp_conversations', ['line_id', 'status', 'last_message_at'], unique=False)
    op.create_table('whatsapp_conversation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assignment_source', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whatsapp_conversation_assignments_conversation_created', 'whatsapp_conversation_assignments', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_whatsapp_conversation_assignments_to_user_id', 'whatsapp_conversation_assignments', ['to_user_id'], unique=False)
    op.create_table('whatsapp_conversation_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    # NOTA: la FK last_read_message_id -> whatsapp_messages NO se declara inline aquí porque
    # whatsapp_conversation_reads se crea ANTES que whatsapp_messages. Se agrega explícitamente
    # con op.create_foreign_key() al final de upgrade(), una vez creadas ambas tablas.
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_whatsapp_conversation_reads_conversation_user')
    )
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('client_request_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('context_external_message_id', sa.String(length=255), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message_safe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whatsapp_messages_conversation_created_at', 'whatsapp_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_whatsapp_messages_conversation_provider_ts', 'whatsapp_messages', ['conversation_id', 'provider_timestamp'], unique=False)
    op.create_index('ix_whatsapp_messages_current_status', 'whatsapp_messages', ['current_status'], unique=False)
    op.create_index('ix_whatsapp_messages_sender_user_id', 'whatsapp_messages', ['sender_user_id'], unique=False)
    op.create_index('uq_whatsapp_messages_client_request_id', 'whatsapp_messages', ['client_request_id'], unique=True, postgresql_where=sa.text('client_request_id IS NOT NULL'))
    op.create_index('uq_whatsapp_messages_provider_external_id', 'whatsapp_messages', ['provider', 'external_message_id'], unique=True, postgresql_where=sa.text('external_message_id IS NOT NULL'))
    op.create_table('whatsapp_message_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('safe_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['whatsapp_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_whatsapp_message_status_events_event_key')
    )
    op.create_index('ix_whatsapp_message_status_events_message_id', 'whatsapp_message_status_events', ['message_id'], unique=False)
    # ### end Alembic commands ###

    # FK circular resuelta explícitamente: se agrega DESPUÉS de crear whatsapp_messages
    # (whatsapp_conversation_reads se creó antes). ondelete=SET NULL para conservar la fila
    # de lectura si el mensaje referido se borrara.
    op.create_foreign_key(
        'fk_whatsapp_conversation_reads_last_read_message_id',
        'whatsapp_conversation_reads',
        'whatsapp_messages',
        ['last_read_message_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    # Primero se elimina la FK circular (conversation_reads -> messages), antes de dropear
    # cualquier tabla, para no chocar con la dependencia al borrar whatsapp_messages.
    op.drop_constraint(
        'fk_whatsapp_conversation_reads_last_read_message_id',
        'whatsapp_conversation_reads',
        type_='foreignkey',
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_whatsapp_message_status_events_message_id', table_name='whatsapp_message_status_events')
    op.drop_table('whatsapp_message_status_events')
    op.drop_index('uq_whatsapp_messages_provider_external_id', table_name='whatsapp_messages', postgresql_where=sa.text('external_message_id IS NOT NULL'))
    op.drop_index('uq_whatsapp_messages_client_request_id', table_name='whatsapp_messages', postgresql_where=sa.text('client_request_id IS NOT NULL'))
    op.drop_index('ix_whatsapp_messages_sender_user_id', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_current_status', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_conversation_provider_ts', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_conversation_created_at', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_table('whatsapp_conversation_reads')
    op.drop_index('ix_whatsapp_conversation_assignments_to_user_id', table_name='whatsapp_conversation_assignments')
    op.drop_index('ix_whatsapp_conversation_assignments_conversation_created', table_name='whatsapp_conversation_assignments')
    op.drop_table('whatsapp_conversation_assignments')
    op.drop_index('ix_whatsapp_conversations_line_status_last_msg', table_name='whatsapp_conversations')
    op.drop_index('ix_whatsapp_conversations_lead_id', table_name='whatsapp_conversations')
    op.drop_index('ix_whatsapp_conversations_contact_id', table_name='whatsapp_conversations')
    op.drop_index('ix_whatsapp_conversations_assigned_status_last_msg', table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    op.drop_index('ix_whatsapp_contact_identifiers_identifier_value', table_name='whatsapp_contact_identifiers')
    op.drop_index('ix_whatsapp_contact_identifiers_contact_id', table_name='whatsapp_contact_identifiers')
    op.drop_table('whatsapp_contact_identifiers')
    op.drop_index('ix_whatsapp_line_user_access_user_id', table_name='whatsapp_line_user_access')
    op.drop_index('ix_whatsapp_line_user_access_line_id', table_name='whatsapp_line_user_access')
    op.drop_table('whatsapp_line_user_access')
    op.drop_index('ix_whatsapp_contacts_lead_id', table_name='whatsapp_contacts')
    op.drop_table('whatsapp_contacts')
    op.drop_index('ix_whatsapp_webhook_events_status_received', table_name='whatsapp_webhook_events')
    op.drop_index('ix_whatsapp_webhook_events_raw_payload_expires_at', table_name='whatsapp_webhook_events')
    op.drop_table('whatsapp_webhook_events')
    op.drop_table('whatsapp_lines')
    # ### end Alembic commands ###
