"""extend_product_model

Revision ID: a7da328604d3
Revises: d50c8f471238
Create Date: 2026-02-22 15:25:20.773761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7da328604d3'
down_revision: Union[str, None] = 'd50c8f471238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('iva_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('products', sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(), nullable=True))
    op.add_column('products', sa.Column('provider_name', sa.String(), nullable=True))
    op.alter_column('products', 'price_wholesale',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'price_retail',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price_retail',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'price_wholesale',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('products', 'provider_name')
    op.drop_column('products', 'color')
    op.drop_column('products', 'length')
    op.drop_column('products', 'width')
    op.drop_column('products', 'height')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'iva_percent')
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
