"""Add SaleOrders and OrderItems

Revision ID: d88928b773ad
Revises: a7da328604d3
Create Date: 2026-03-06 21:30:27.151453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88928b773ad'
down_revision: Union[str, None] = 'a7da328604d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('dni_cuit', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('address', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('locality', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('province', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('zip_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'zip_code')
    op.drop_column('leads', 'province')
    op.drop_column('leads', 'locality')
    op.drop_column('leads', 'address')
    op.drop_column('leads', 'dni_cuit')
    # ### end Alembic commands ###
